# Generated by Django 2.1 on 2018-08-21 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data_dodania')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data_modyfikacji')),
                ('is_published', models.BooleanField(default=True, verbose_name='Opublikowano?')),
                ('offer_number', models.IntegerField(blank=True, null=True, verbose_name='numer_oferty')),
                ('property_type', models.CharField(choices=[('dom', 'Dom'), ('mieszkanie', 'Mieszkanie'), ('lokal', 'Lokal'), ('działka', 'Działka'), ('obiekt', 'Obiekt')], max_length=50)),
                ('transaction_type', models.CharField(choices=[('sprzedaz', 'Sprzedaz'), ('wynajem', 'Wynajem')], max_length=10, verbose_name='rodzaj_transakcji')),
                ('slug', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('square_meter', models.IntegerField(blank=True, null=True)),
                ('area', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='opis')),
                ('price', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='cena')),
                ('price_per_square_meter', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='cena')),
                ('choices', models.IntegerField(blank=True, choices=[(0, 'Na_sprzedaz'), (1, 'W_trakcie_sprzedazy'), (2, 'Sprzedane')], null=True)),
                ('build_in_year', models.IntegerField(blank=True, null=True, verbose_name='rok_budowy')),
                ('rooms', models.IntegerField(blank=True, null=True, verbose_name='liczba_pokoi')),
                ('floor', models.IntegerField(blank=True, null=True, verbose_name='pietro')),
                ('number_floors', models.IntegerField(blank=True, null=True, verbose_name='liczba_pieter')),
                ('driveway', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'property',
                'verbose_name_plural': 'properties',
            },
        ),
        migrations.CreateModel(
            name='PropertyManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='arkadia.Property')),
            ],
            options={
                'abstract': False,
            },
            bases=('arkadia.property',),
        ),
        migrations.CreateModel(
            name='Commercial',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='arkadia.Property')),
            ],
            options={
                'abstract': False,
            },
            bases=('arkadia.property',),
        ),
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='arkadia.Property')),
            ],
            options={
                'abstract': False,
            },
            bases=('arkadia.property',),
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='arkadia.Property')),
            ],
            options={
                'abstract': False,
            },
            bases=('arkadia.property',),
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='arkadia.Property')),
            ],
            options={
                'abstract': False,
            },
            bases=('arkadia.property',),
        ),
    ]
