# Generated by Django 2.1 on 2018-08-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arkadia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Pow. działki'),
        ),
        migrations.AlterField(
            model_name='property',
            name='build_in_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Rok budowy'),
        ),
        migrations.AlterField(
            model_name='property',
            name='choices',
            field=models.CharField(blank=True, choices=[(0, 'Na sprzedaz'), (1, 'W trakcie sprzedazy'), (2, 'Sprzedane')], max_length=20, null=True, verbose_name='Rodzaj transakcji'),
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Miasto'),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='property',
            name='driveway',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Droga dojazdowa'),
        ),
        migrations.AlterField(
            model_name='property',
            name='floor',
            field=models.IntegerField(blank=True, null=True, verbose_name='Piętro'),
        ),
        migrations.AlterField(
            model_name='property',
            name='number_floors',
            field=models.IntegerField(blank=True, null=True, verbose_name='Liczba pięter'),
        ),
        migrations.AlterField(
            model_name='property',
            name='offer_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Numer oferty'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Cena'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price_per_square_meter',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Cena za metr'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('dom', 'Dom'), ('mieszkanie', 'Mieszkanie'), ('lokal', 'Lokal'), ('działka', 'Działka'), ('obiekt', 'Obiekt')], max_length=50, verbose_name='Typ nieruchomości'),
        ),
        migrations.AlterField(
            model_name='property',
            name='rooms',
            field=models.IntegerField(blank=True, null=True, verbose_name='Liczba pokoi'),
        ),
        migrations.AlterField(
            model_name='property',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='square_meter',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Powierzchnia'),
        ),
        migrations.AlterField(
            model_name='property',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Województwo'),
        ),
        migrations.AlterField(
            model_name='property',
            name='transaction_type',
            field=models.CharField(choices=[('sprzedaz', 'Sprzeda'), ('wynajem', 'Wynajem')], max_length=20, verbose_name='Rodzaj transakcji'),
        ),
    ]
