# Generated by Django 2.1 on 2018-08-22 19:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('arkadia', '0003_auto_20180821_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 22, 19, 7, 11, 997753, tzinfo=utc), verbose_name='Data wprowadzenia'),
        ),
        migrations.AlterField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data dodania'),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Wprowadzono?'),
        ),
        migrations.AlterField(
            model_name='property',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data modyfikacji'),
        ),
    ]
