# Generated by Django 2.1 on 2018-08-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arkadia', '0004_auto_20180822_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='published_at',
            field=models.DateTimeField(verbose_name='Data wprowadzenia'),
        ),
    ]
